# Tokyo Night Dark colors for fish syntax highlighting
set -g fish_color_autosuggestion  414868
set -g fish_color_cancel          -r
set -g fish_color_command         7aa2f7
set -g fish_color_comment         565f89
set -g fish_color_cwd             ff5e7d
set -g fish_color_cwd_root        f7768e
set -g fish_color_end             bb9af7
set -g fish_color_error           f7768e
set -g fish_color_escape          7dcfff
set -g fish_color_history_current --bold
set -g fish_color_host            normal
set -g fish_color_normal          normal
set -g fish_color_operator        7dcfff
set -g fish_color_param           c0caf5
set -g fish_color_quote           9ece6a
set -g fish_color_redirection     bb9af7
set -g fish_color_search_match    --background=3b4261
set -g fish_color_selection       --background=3b4261
set -g fish_color_user            brgreen
set -g fish_color_valid_path      --underline
