;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;==========================================================

[global/wm]
include-file = $HOME/.config/polybar/colors.ini
include-file = $HOME/.config/polybar/modules.ini

; Setting up the main laptop monitor
[bar/top]
monitor = HDMI-A-0
tray-position = none
tray-padding = 5
width = 100%
height = 18
padding-left = 1
padding-right = 0
background = ${colors.jp-bg}
foreground = ${colors.jp-text}
bottom = false
border-top-size = 7
border-bottom-size = 7
border-top-color = ${colors.jp-bg}
border-bottom-color = ${colors.jp-bg}
offset-x = 0%
offset-y = 0.5%
fixed-center = true
line-size = 3
wm-restack = bspwm

modules-left = logo bspwm sep focused_app
modules-right = ethernet sep gpu sep memory sep alsa sep time space powermenu

font-0 = JetBrainsMono Nerd Font:style=Bold:pixelsize=9;3
font-1 = JetBrainsMono Nerd Font:size=11;5
font-2 = Material Design Icons:style=Bold:size=9;3
font-3 = unifont:fontformat=truetype:size=9:antialias=true;
font-4 = Noto Sans CJK JP:size=9;3

; Launch for 4k monitor
[bar/top_external]
monitor = HDMI-A-1-0
tray-position = none
tray-padding = 5
width = 100%
height = 18
padding-left = 1
padding-right = 0
background = ${colors.jp-bg}
foreground = ${colors.jp-text}
bottom = false
border-top-size = 7
border-bottom-size = 7
border-top-color = ${colors.jp-bg}
border-bottom-color = ${colors.jp-bg}
offset-x = 0%
offset-y = 0.5%
fixed-center = true
line-size = 3
wm-restack = bspwm

modules-left = logo bspwm sep focused_app
modules-right = ethernet sep gpu sep memory sep alsa sep time space powermenu

font-0 = JetBrainsMono Nerd Font:style=Bold:pixelsize=9;3
font-1 = JetBrainsMono Nerd Font:size=11;5
font-2 = Material Design Icons:style=Bold:size=9;3
font-3 = unifont:fontformat=truetype:size=9:antialias=true;
font-4 = Noto Sans CJK JP:size=9;3
